CREATE TABLE IF NOT EXISTS ads (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    item_count INTEGER NOT NULL,
    average_rating DECIMAL(3, 2) DEFAULT 0.0,
    ratings_count INTEGER DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
