CREATE TABLE IF NOT EXISTS media (
    id TEXT PRIMARY KEY NOT NULL UNIQUE,
    parent_id TEXT NOT NULL,
    url TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)